### ISSUE TITLE
Screenshots are switched around.

### ISSUE THREAD

**Issue by magnetophon** [DISTRHO/OneKnob-Series#1]
Thanks for another set of plugins!

Small heads up:
The [limiter screenshot](https://github.com/DISTRHO/OneKnob-Series/raw/main/plugins/BrickWallLimiter/Screenshot.png) contains the compressor and vise versa.

**Comment by falkTX** [comment]
the plugins are far from complete, as they stand right now they are just toys.
they exist mainly for me to test new DPF and DPF-Widgets repo, it will be a few more weeks until they are finalized if that ever happens

**Comment by falkTX** [comment]
FIxed now.
FYI a port of barry's satan maximizer from swh-plugins is in place now. UI is still WIP.
