### ISSUE TITLE
ConvolutionReverb/MOD-ConvolutionLoader.lv2 if ir length <= tail size plugin crashes the plugin's host

### ISSUE THREAD

**Issue by MaxPayne86** [DISTRHO/OneKnob-Series#7]
[This](https://github.com/AidaDSP/aidadsp-lv2/blob/main/irs/Vintage/Under%20Water%20IR.wav) IR file is 1024 samples. Tested on Mod Dwarf. While troubleshooting a PR I've found out the code crashes in FFTConvolver.cpp, section below

```
// Prepare IR
  for (size_t i=0; i<_segCount; ++i)
  {
    SplitComplex* segment = new SplitComplex(_fftComplexSize);
    const size_t remaining = irLen - (i * _blockSize);
    const size_t sizeCopy = (remaining >= _blockSize) ? _blockSize : remaining;
    CopyAndPad(_fftBuffer, &ir[i*_blockSize], sizeCopy);
    _fft.fft(_fftBuffer.data(), segment->re(), segment->im());
    _segmentsIR.push_back(segment);
  }
```
you may want to promptly add a stupid control since the final user won't check the IR length. I don't know if I will be able to finish my PR since I've already tried (in case numFrames < tail) with no luck:

1. allocate an ir file bigger (*2) by adding zeros at the end
2. refactor head = numFrames/128 tail = numFrames/32 (random power of two numbers)

I think the first is not working since there are multiple parts in the code where zeros at the end are cutted from the processed ir file. The second should have worked but it didn't and I don't know when I will be able to work on it again ;(

**Comment by falkTX** [comment]
Fixed in 3f1a9e169a1c6e7a0ef64107c7cd1010719c32fb importing the improved convolver class.
On very small IRs dealing with multi-threading is counter-productive, and fixes the issue for us anyway.
